### ISSUE TITLE
MyInfo V4

### ISSUE THREAD

**Issue by bryanongjxCH** [GovTechSG/myinfo-rails#30]
Implement a connector for MyInfo V4 that has the following major changes:

1. PKCE
2. Client Assertion
3. JWKS
4. DPoP

**Comment by bryanongjxCH** [comment]
Hey guys! We are migrating from V3 to V4 and we are planning to make an open source contribution to this repo. Hope to hear your thoughts on this! :) @kmye @causztic @sampradeep

**Comment by kmye** [comment]
Hi @bryanongjxCH yes sure! feel free to open a PR 🙂

**Comment by bryanongjxCH** [comment]
sounds good! :)

**Comment by shivasingh21** [comment]
Hi @bryanongjxCH 
Can you please let me know when the upgrade from V3 to V4 is likely to be finished as the end of support date for V3 is 1 April 2024.

**Comment by kmye** [comment]
> Hi @bryanongjxCH Can you please let me know when the upgrade from V3 to V4 is likely to be finished as the end of support date for V3 is 1 April 2024.

Hello @shivasingh21  thanks for the interest.. looks like @bryanongjxCH is inactive. I am working on it at the moment. 😄

**Comment by shivasingh21** [comment]
@kmye Thanks for the update.

**Comment by kmye** [comment]
@shivasingh21 

Hello! sorry to keep you waiting, I just release 0.6.0 to support myinfo v4. lmk if you encounter any issues with the gem. 

Happy holidays!
